<a href="https://colab.research.google.com/github/vivekk2k28/Machine_Learning/blob/main/Regression/Decision%20Tree%20Regression/decision_tree_regression_Life_Expectancy_WHO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Decision Tree Regression

## Importing the libraries

In [94]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [95]:
dataset = pd.read_csv('Life Expectancy Data.csv')
X = dataset.drop(columns=['Life expectancy ']).values  # Assuming the column name has trailing space
y = dataset['Life expectancy '].values  # Assuming the column name has trailing space

In [96]:
print(X)

[['Afghanistan' 2015 'Developing' ... 17.3 0.479 10.1]
 ['Afghanistan' 2014 'Developing' ... 17.5 0.476 10.0]
 ['Afghanistan' 2013 'Developing' ... 17.7 0.47 9.9]
 ...
 ['Zimbabwe' 2002 'Developing' ... 1.3 0.427 10.0]
 ['Zimbabwe' 2001 'Developing' ... 1.7 0.427 9.8]
 ['Zimbabwe' 2000 'Developing' ... 11.2 0.434 9.8]]


In [97]:
print(y)

[65.  59.9 59.9 ... 44.8 45.3 46. ]


In [98]:
# Check for missing values in all columns
missing_values = dataset.isnull().sum()
print(missing_values)

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64


#Encoding the Independent variable

In [99]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 'Afghanistan' ... 17.3 0.479 10.1]
 [0.0 1.0 'Afghanistan' ... 17.5 0.476 10.0]
 [0.0 1.0 'Afghanistan' ... 17.7 0.47 9.9]
 ...
 [0.0 1.0 'Zimbabwe' ... 1.3 0.427 10.0]
 [0.0 1.0 'Zimbabwe' ... 1.7 0.427 9.8]
 [0.0 1.0 'Zimbabwe' ... 11.2 0.434 9.8]]


In [100]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [101]:
print(X)

[[0.0 1.0 0 ... 17.3 0.479 10.1]
 [0.0 1.0 0 ... 17.5 0.476 10.0]
 [0.0 1.0 0 ... 17.7 0.47 9.9]
 ...
 [0.0 1.0 192 ... 1.3 0.427 10.0]
 [0.0 1.0 192 ... 1.7 0.427 9.8]
 [0.0 1.0 192 ... 11.2 0.434 9.8]]


In [102]:
from sklearn.impute import SimpleImputer
# For feature matrix X
imputer_X = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer_X.fit(X)
X = imputer_X.transform(X)

In [106]:
# Reshape y to a 2D array with a single column
y_reshaped = y.reshape(-1, 1)

# Initialize SimpleImputer and fit on y
imputer_y = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer_y.fit(y_reshaped)

# Transform y using the fitted imputer
y_transformed = imputer_y.transform(y_reshaped)
y = y_transformed.flatten()

In [107]:
missing_values = np.isnan(X)

# Sum the missing values along each column
missing_values_count = np.sum(missing_values, axis=0)

print("Missing values in each column:")
print(missing_values_count)

Missing values in each column:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [108]:
missing_values = np.isnan(y)

# Sum the missing values along each column
missing_values_count = np.sum(missing_values, axis=0)

print("Missing values in each column:")
print(missing_values_count)

Missing values in each column:
0


#Splitting the dataset into the Training set and Test set:

In [109]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state = 0)

In [110]:
print(y_train)

[63.1 59.2 72.  ... 62.7 66.6 71. ]


## Training the Decision Tree Regression model on the whole dataset

In [111]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

In [113]:
print(X_train)

[[  0.      1.    147.    ...   7.6     0.501   9.6  ]
 [  0.      1.      0.    ...  18.2     0.454   9.5  ]
 [  1.      0.     97.    ...   3.      0.812  16.4  ]
 ...
 [  0.      1.    106.    ...   7.9     0.501   8.2  ]
 [  0.      1.    171.    ...  11.6     0.599  12.1  ]
 [  0.      1.    180.    ...   2.4     0.744  15.2  ]]


## Predicting a new result

In [115]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_pred), 1)), 1))


[[77.6 77.3]
 [66.6 66.6]
 [53.1 52.6]
 ...
 [78.7 82. ]
 [48.5 54. ]
 [73.8 73.9]]


In [117]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Calculate mean squared error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

# Calculate mean absolute error
mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error:", mae)

# Calculate R-squared score
r2 = r2_score(y_test, y_pred)
print("R-squared Score:", r2)


Mean Squared Error: 8.337450763924817
Mean Absolute Error: 1.7034695736217984
R-squared Score: 0.9110385372811263
